[tool.poetry]
name = "chrispy"
version = "0.2.1"
description = "A dummy Python repository to mess around in."
authors = ["KrisGj <chris.gjurgjinoski@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
Flask = "3.1.2"
gunicorn = "23.0.0"
poetry-core = "2.2.1"
python = "3.13.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
