[tool.poetry]
name = "chrispy"
version = "0.2.1"
description = "A dummy Python repository to mess around in."
authors = ["KrisGj <chris.gjurgjinoski@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
alembic = "1.17.2"
Flask = "3.1.2"
Flask-Migrate = "4.1.0"
Flask-SQLAlchemy = "3.1.1"
gunicorn = "23.0.0"
poetry-core = "2.2.1"
psycopg = "3.3.2"
python = "3.13.6"
python-decouple = "3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
